# Config file to run and test a simple "Calculator" program in an Anaconda virtual environment with Travis CI

language: python

python:
 - "3.6"

install:
 - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - source "$HOME/miniconda/etc/profile.d/conda.sh"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a

before_script:
 - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip
 - conda activate test-environment
 - pip install pytest
 - pip install pytest-cov
 - pip install coverage

script:
 - pytest -v test_calculator.py --cov=./

after_success:
 - bash <(curl -s https://codecov.io/bash)